# Generated by Django 3.1.6 on 2021-02-02 18:41

from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20210202_2209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_posted',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True),
        ),
    ]
