# Generated by Django 3.1.6 on 2021-02-02 18:47

from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20210202_2217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_posted',
            field=django_jalali.db.models.jDateTimeField(),
        ),
    ]
