# Generated by Django 3.1.6 on 2021-02-02 23:06

from django.db import migrations
import django.utils.timezone
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20210203_0011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_posted',
            field=django_jalali.db.models.jDateTimeField(default=django.utils.timezone.now),
        ),
    ]
